version: "3"
services:
  ubuntu_node:
    build: .
    container_name: ubuntu_node
    image: base
    ports:
      - "20022:22"
  puppet_5_node:
    container_name: puppet_5_node
    depends_on: [ubuntu_node]
    image: puppet5
    ports:
      - "20023:22"
  puppet_6_node:
    container_name: puppet_6_node
    depends_on: [ubuntu_node]
    image: puppet6
    ports:
      - "20024:22"
  puppet_7_node:
    container_name: puppet_7_node
    depends_on: [ubuntu_node]
    image: puppet7
    ports:
      - "20025:22"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    volumes:
      - ./fixtures/puppetdb/custom_source:/docker-entrypoint-initdb.d

  puppetdb:
    build:
      context: .
      dockerfile: Dockerfile.puppetdb
      args:
        hostname: bolt-puppetdb
    environment:
      - "USE_PUPPETSERVER=false"
      - "CERTNAME=pdb"
    image: puppetdb
    ports:
      # 8081 is a common port
      - "18081:8081"

  puppetserver:
    build:
      context: .
      dockerfile: Dockerfile.puppetserver
    image: puppet-server
    ports:
      - "8140:8140"
    volumes:
      - ./fixtures/modules:/etc/puppetlabs/code/modules
