#!/usr/bin/env ruby
# frozen_string_literal: true

ENV['BOOTSNAP_CACHE_DIR'] = begin
  if RbConfig::CONFIG['host_os'] =~/mswin|mingw|cygwin/
    File.join(ENV['ProgramData'], 'Puppetlabs', 'bolt')
  else
    File.expand_path('~/.puppetlabs/etc/bolt')
  end
rescue StandardError; end

unless ENV['BOOTSNAP_CACHE_DIR']
  require 'bootsnap'

  Bootsnap.setup(
    cache_dir:            ENV['BOOTSNAP_CACHE_DIR'],
    development_mode:     false,
    load_path_cache:      true,
    compile_cache_iseq:   true,
    compile_cache_yaml:   false
  )
end

require 'bolt'
require 'bolt/cli'

Thread.current[:name] ||= 'main'
cli = Bolt::CLI.new(ARGV)
begin
  opts = cli.parse
  exitcode = cli.execute(opts)
  exit exitcode
rescue Bolt::CLIExit
  exit
rescue Bolt::Error => e
  exit e.error_code
end
