name: Linux build

on: [push]

env:
  REGISTRY_HOST: pcr-internal.puppet.net
  DOCKER_REGISTRY: pe-and-platform
  BOLT_SUDO_USER: true

jobs:

  modules:
    name: Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Run module tests
        run: bundle exec rake github:modules

  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Pre-test setup
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.23.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          echo 'runner:runner' | sudo chpasswd
          sudo sh -c "echo 'Defaults authenticate' >> /etc/sudoers"
          sudo sh -c "echo 'runner  ALL=(ALL) PASSWD:ALL' >> /etc/sudoers"
          docker-compose -f spec/docker-compose.yml build --parallel ubuntu_node puppet_5_node puppet_6_node
          docker-compose -f spec/docker-compose.yml up -d ubuntu_node puppet_5_node puppet_6_node
      - name: Run unit tests
        run: bundle exec rake github:unit

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Pre-test setup
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.23.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -f spec/docker-compose.yml build --parallel
          docker-compose -f spec/docker-compose.yml up -d
      - name: Run integration tests
        run: bundle exec rake github:integration
